import { app, BrowserWindow, ipcMain, dialog } from "electron";
import path from "path";
import fs from "fs/promises";
import simpleGit from "simple-git";
import chokidar from "chokidar";

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  //   mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  createWindow();
  await setupWatcher();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Helper functions
const getAppDataPath = (): string => {
  return path.join(app.getPath("userData"), "tracked-files");
};

const getTrackedFilesPath = (): string => {
  return path.join(getAppDataPath(), "tracked.json");
};

const ensureDir = async (dirPath: string): Promise<void> => {
  try {
    await fs.access(dirPath);
  } catch {
    await fs.mkdir(dirPath, { recursive: true });
  }
};

const getRepoPath = (filePath: string): string => {
  const fileHash = Buffer.from(filePath)
    .toString("base64")
    .replace(/[/+=]/g, "_");
  return path.join(getAppDataPath(), fileHash);
};

const loadTrackedFiles = async (): Promise<string[]> => {
  try {
    const data = await fs.readFile(getTrackedFilesPath(), "utf-8");
    return JSON.parse(data);
  } catch {
    return [];
  }
};

let watcher: ReturnType<typeof chokidar.watch> | null = null;

const setupWatcher = async (): Promise<void> => {
  const trackedFiles = await loadTrackedFiles();

  watcher = chokidar.watch(trackedFiles, {
    persistent: true,
    ignoreInitial: true,
  });

  watcher.on("unlink", (filePath) => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("file-missing", filePath);
    }
  });
};

const initRepo = async (filePath: string): Promise<string> => {
  const repoPath = getRepoPath(filePath);
  await ensureDir(repoPath);

  const git = simpleGit(repoPath);
  const isRepo = await git.checkIsRepo();

  if (!isRepo) {
    await git.init();
    await git.addConfig("user.name", "Version Tracker");
    await git.addConfig("user.email", "tracker@local");
  }

  return repoPath;
};

// IPC Handlers
ipcMain.handle("select-file", async () => {
  if (!mainWindow) return null;

  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ["openFile"],
  });

  if (!result.canceled && result.filePaths.length > 0) {
    return result.filePaths[0];
  }
  return null;
});

ipcMain.handle("track-file", async (event, filePath: string) => {
  try {
    await initRepo(filePath);

    const trackedFilesPath = getTrackedFilesPath();
    await ensureDir(getAppDataPath());

    let trackedFiles: string[] = [];
    try {
      const data = await fs.readFile(trackedFilesPath, "utf-8");
      trackedFiles = JSON.parse(data);
    } catch {
      // File doesn't exist yet
    }

    if (!trackedFiles.includes(filePath)) {
      trackedFiles.push(filePath);
      await fs.writeFile(
        trackedFilesPath,
        JSON.stringify(trackedFiles, null, 2),
      );
      watcher?.add(filePath);
    }

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle("get-tracked-files", async () => {
  return loadTrackedFiles();
});

/* 
event: This object contains information about the sender (like which window sent the message). You usually don't need to use it unless you're verifying security or replying to a specific frame.
*/

ipcMain.handle("check-file-changes", async (event, filePath: string) => {
  const repoPath = getRepoPath(filePath);
  const targetFilePath = path.join(repoPath, path.basename(filePath));

  await fs.copyFile(filePath, targetFilePath);

  const git = simpleGit(repoPath);

  const hasAnyCommits = await git
    .raw(["rev-parse", "HEAD"])
    .then(() => true)
    .catch(() => false);
  if (!hasAnyCommits) {
    return { hasChanges: true };
  }

  const status = await git.status();
  const hasChanges =
    status.modified.length > 0 ||
    status.created.length > 0 ||
    status.not_added.length > 0;

  return { hasChanges };
});

ipcMain.handle(
  "commit-version",
  async (event, filePath: string, message: string) => {
    try {
      const repoPath = getRepoPath(filePath);
      const targetFilePath = path.join(repoPath, path.basename(filePath));

      await fs.copyFile(filePath, targetFilePath);

      const git = simpleGit(repoPath);
      await git.add(".");

      let commitMessage = message;
      if (!commitMessage) {
        const log = await git.log();
        const versionNumber = log.all.length + 1;
        commitMessage = `V${versionNumber}`;
      }

      await git.commit(commitMessage);

      return { success: true };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle(
  "rename-last-version",
  async (event, filePath: string, newMessage: string) => {
    try {
      const repoPath = getRepoPath(filePath);
      const git = simpleGit(repoPath);

      // Amend the last commit with new message
      await git.commit(newMessage, undefined, { "--amend": null });

      return { success: true };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle("get-versions", async (event, filePath: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const git = simpleGit(repoPath);

    const log = await git.log();

    return log.all.map((commit) => ({
      hash: commit.hash,
      message: commit.message,
      date: commit.date,
      author: commit.author_name,
    }));
  } catch {
    return [];
  }
});

ipcMain.handle(
  "restore-version",
  async (event, filePath: string, commitHash: string) => {
    try {
      const repoPath = getRepoPath(filePath);
      const git = simpleGit(repoPath);

      const fileName = path.basename(filePath);
      const fileContent = await git.show([`${commitHash}:${fileName}`]);

      await fs.writeFile(filePath, fileContent);

      return { success: true };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle("remove-tracked-file", async (event, filePath: string) => {
  try {
    const trackedFiles = await loadTrackedFiles();
    const updated = trackedFiles.filter((f) => f !== filePath);
    await fs.writeFile(getTrackedFilesPath(), JSON.stringify(updated, null, 2));
    watcher?.unwatch(filePath);
    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle("delete-file-history", async (event, filePath: string) => {
  try {
    const trackedFiles = await loadTrackedFiles();
    const updated = trackedFiles.filter((f) => f !== filePath);
    await fs.writeFile(getTrackedFilesPath(), JSON.stringify(updated, null, 2));
    await fs.rm(getRepoPath(filePath), { recursive: true, force: true });
    watcher?.unwatch(filePath);
    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle(
  "export-version",
  async (
    event,
    filePath: string,
    commitHash: string,
    versionMessage: string,
  ) => {
    try {
      if (!mainWindow) return { success: false, error: "No main window" };

      const repoPath = getRepoPath(filePath);
      const git = simpleGit(repoPath);

      const fileName = path.basename(filePath);
      const fileContent = await git.show([`${commitHash}:${fileName}`]);

      const parsedPath = path.parse(filePath);
      const ext = parsedPath.ext;
      const nameWithoutExt = parsedPath.name;
      const dir = parsedPath.dir;

      const versionLabel = versionMessage.replace(/[^a-zA-Z0-9]/g, "_");
      const suggestedName = `${nameWithoutExt}_${versionLabel}${ext}`;

      const result = await dialog.showSaveDialog(mainWindow, {
        defaultPath: path.join(dir, suggestedName),
        filters: [{ name: "All Files", extensions: ["*"] }],
      });

      if (!result.canceled && result.filePath) {
        await fs.writeFile(result.filePath, fileContent);
        return { success: true, path: result.filePath };
      }

      return { success: false, error: "Export cancelled" };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle(
  "get-diff",
  async (event, filePath: string, commitHash: string) => {
    try {
      const repoPath = getRepoPath(filePath);
      const git = simpleGit(repoPath);
      const fileName = path.basename(filePath);

      const diff = await git.raw([
        "diff-tree",
        "--no-commit-id",
        "-p",
        commitHash,
        "--",
        fileName,
      ]);
      return { success: true, diff };
    } catch (error) {
      return { success: false, error: (error as Error).message, diff: "" };
    }
  },
);

ipcMain.handle(
  "relink-file",
  async (event, oldPath: string, newPath: string) => {
    try {
      const oldRepoPath = getRepoPath(oldPath);
      const newRepoPath = getRepoPath(newPath);
      await fs.rename(oldRepoPath, newRepoPath);

      const trackedFiles = await loadTrackedFiles();
      const updated = trackedFiles.map((f) => (f === oldPath ? newPath : f));
      await fs.writeFile(
        getTrackedFilesPath(),
        JSON.stringify(updated, null, 2),
      );

      watcher?.unwatch(oldPath);
      watcher?.add(newPath);

      return { success: true };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle(
  "start-fresh",
  async (event, oldPath: string, newPath: string) => {
    try {
      const trackedFiles = await loadTrackedFiles();
      const updated = trackedFiles.filter((f) => f !== oldPath);
      if (!updated.includes(newPath)) updated.push(newPath);
      await fs.writeFile(
        getTrackedFilesPath(),
        JSON.stringify(updated, null, 2),
      );

      await initRepo(newPath);

      watcher?.unwatch(oldPath);
      watcher?.add(newPath);

      return { success: true };
    } catch (error) {
      return { success: false, error: (error as Error).message };
    }
  },
);

ipcMain.handle(
  "get-last-version-content",
  async (event, filePath: string) => {
    try {
      const repoPath = getRepoPath(filePath);
      const git = simpleGit(repoPath);
      const fileName = path.basename(filePath);
      const content = await git.show([`HEAD:${fileName}`]);
      return { success: true, content };
    } catch {
      return { success: false, content: "" };
    }
  },
);

ipcMain.handle("check-missing-files", async (event, filePaths: string[]) => {
  const missing: string[] = [];
  for (const filePath of filePaths) {
    try {
      await fs.access(filePath);
    } catch {
      missing.push(filePath);
    }
  }
  return missing;
});

ipcMain.handle("get-preference", async (event, key: string) => {
  try {
    const preferencesPath = path.join(getAppDataPath(), "preferences.json");
    await ensureDir(getAppDataPath());

    try {
      const data = await fs.readFile(preferencesPath, "utf-8");
      const preferences = JSON.parse(data);
      return preferences[key];
    } catch {
      return null;
    }
  } catch {
    return null;
  }
});

ipcMain.handle("set-preference", async (event, key: string, value: any) => {
  try {
    const preferencesPath = path.join(getAppDataPath(), "preferences.json");
    await ensureDir(getAppDataPath());

    let preferences: Record<string, any> = {};
    try {
      const data = await fs.readFile(preferencesPath, "utf-8");
      preferences = JSON.parse(data);
    } catch {
      // File doesn't exist yet
    }

    preferences[key] = value;
    await fs.writeFile(preferencesPath, JSON.stringify(preferences, null, 2));

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});
