import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import path from 'path';
import fs from 'fs/promises';
import simpleGit from 'simple-git';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

let mainWindow: BrowserWindow | null = null;

const createWindow = (): void => {
  // Create the browser window.
  mainWindow = new BrowserWindow({
    height: 800,
    width: 1200,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      contextIsolation: true,
      nodeIntegration: false,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// Helper functions
const getAppDataPath = (): string => {
  return path.join(app.getPath('userData'), 'tracked-files');
};

const ensureDir = async (dirPath: string): Promise<void> => {
  try {
    await fs.access(dirPath);
  } catch {
    await fs.mkdir(dirPath, { recursive: true });
  }
};

const getRepoPath = (filePath: string): string => {
  const fileHash = Buffer.from(filePath).toString('base64').replace(/[/+=]/g, '_');
  return path.join(getAppDataPath(), fileHash);
};

const initRepo = async (filePath: string): Promise<string> => {
  const repoPath = getRepoPath(filePath);
  await ensureDir(repoPath);

  const git = simpleGit(repoPath);
  const isRepo = await git.checkIsRepo();

  if (!isRepo) {
    await git.init();
    await git.addConfig('user.name', 'Version Tracker');
    await git.addConfig('user.email', 'tracker@local');
  }

  return repoPath;
};

// IPC Handlers
ipcMain.handle('select-file', async () => {
  if (!mainWindow) return null;

  const result = await dialog.showOpenDialog(mainWindow, {
    properties: ['openFile']
  });

  if (!result.canceled && result.filePaths.length > 0) {
    return result.filePaths[0];
  }
  return null;
});

ipcMain.handle('track-file', async (event, filePath: string) => {
  try {
    await initRepo(filePath);

    const trackedFilesPath = path.join(getAppDataPath(), 'tracked.json');
    await ensureDir(getAppDataPath());

    let trackedFiles: string[] = [];
    try {
      const data = await fs.readFile(trackedFilesPath, 'utf-8');
      trackedFiles = JSON.parse(data);
    } catch {
      // File doesn't exist yet
    }

    if (!trackedFiles.includes(filePath)) {
      trackedFiles.push(filePath);
      await fs.writeFile(trackedFilesPath, JSON.stringify(trackedFiles, null, 2));
    }

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('get-tracked-files', async () => {
  try {
    const trackedFilesPath = path.join(getAppDataPath(), 'tracked.json');
    const data = await fs.readFile(trackedFilesPath, 'utf-8');
    return JSON.parse(data);
  } catch {
    return [];
  }
});

ipcMain.handle('check-file-changes', async (event, filePath: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const targetFilePath = path.join(repoPath, path.basename(filePath));

    // Copy the current file to the repo to check for changes
    await fs.copyFile(filePath, targetFilePath);

    const git = simpleGit(repoPath);

    // Check if there are any changes
    const status = await git.status();
    const diff = await git.diff(['--cached', targetFilePath]);
    const diffUnstaged = await git.diff([targetFilePath]);

    const hasChanges = status.modified.length > 0 ||
                       status.created.length > 0 ||
                       diff.length > 0 ||
                       diffUnstaged.length > 0;

    return { hasChanges };
  } catch (error) {
    // If there's an error (like no commits yet), assume there are changes
    return { hasChanges: true };
  }
});

ipcMain.handle('commit-version', async (event, filePath: string, message: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const targetFilePath = path.join(repoPath, path.basename(filePath));

    await fs.copyFile(filePath, targetFilePath);

    const git = simpleGit(repoPath);
    await git.add('.');

    let commitMessage = message;
    if (!commitMessage) {
      const log = await git.log();
      const versionNumber = log.all.length + 1;
      commitMessage = `V${versionNumber}`;
    }

    await git.commit(commitMessage);

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('rename-last-version', async (event, filePath: string, newMessage: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const git = simpleGit(repoPath);

    // Amend the last commit with new message
    await git.commit(newMessage, undefined, { '--amend': null });

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('get-versions', async (event, filePath: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const git = simpleGit(repoPath);

    const log = await git.log();

    return log.all.map(commit => ({
      hash: commit.hash,
      message: commit.message,
      date: commit.date,
      author: commit.author_name
    }));
  } catch {
    return [];
  }
});

ipcMain.handle('restore-version', async (event, filePath: string, commitHash: string) => {
  try {
    const repoPath = getRepoPath(filePath);
    const git = simpleGit(repoPath);

    const fileName = path.basename(filePath);
    const fileContent = await git.show([`${commitHash}:${fileName}`]);

    await fs.writeFile(filePath, fileContent);

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('remove-tracked-file', async (event, filePath: string) => {
  try {
    const trackedFilesPath = path.join(getAppDataPath(), 'tracked.json');
    const data = await fs.readFile(trackedFilesPath, 'utf-8');
    let trackedFiles: string[] = JSON.parse(data);

    trackedFiles = trackedFiles.filter(f => f !== filePath);
    await fs.writeFile(trackedFilesPath, JSON.stringify(trackedFiles, null, 2));

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('export-version', async (event, filePath: string, commitHash: string, versionMessage: string) => {
  try {
    if (!mainWindow) return { success: false, error: 'No main window' };

    const repoPath = getRepoPath(filePath);
    const git = simpleGit(repoPath);

    const fileName = path.basename(filePath);
    const fileContent = await git.show([`${commitHash}:${fileName}`]);

    const parsedPath = path.parse(filePath);
    const ext = parsedPath.ext;
    const nameWithoutExt = parsedPath.name;
    const dir = parsedPath.dir;

    const versionLabel = versionMessage.replace(/[^a-zA-Z0-9]/g, '_');
    const suggestedName = `${nameWithoutExt}_${versionLabel}${ext}`;

    const result = await dialog.showSaveDialog(mainWindow, {
      defaultPath: path.join(dir, suggestedName),
      filters: [{ name: 'All Files', extensions: ['*'] }]
    });

    if (!result.canceled && result.filePath) {
      await fs.writeFile(result.filePath, fileContent);
      return { success: true, path: result.filePath };
    }

    return { success: false, error: 'Export cancelled' };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});

ipcMain.handle('get-preference', async (event, key: string) => {
  try {
    const preferencesPath = path.join(getAppDataPath(), 'preferences.json');
    await ensureDir(getAppDataPath());

    try {
      const data = await fs.readFile(preferencesPath, 'utf-8');
      const preferences = JSON.parse(data);
      return preferences[key];
    } catch {
      return null;
    }
  } catch {
    return null;
  }
});

ipcMain.handle('set-preference', async (event, key: string, value: any) => {
  try {
    const preferencesPath = path.join(getAppDataPath(), 'preferences.json');
    await ensureDir(getAppDataPath());

    let preferences: Record<string, any> = {};
    try {
      const data = await fs.readFile(preferencesPath, 'utf-8');
      preferences = JSON.parse(data);
    } catch {
      // File doesn't exist yet
    }

    preferences[key] = value;
    await fs.writeFile(preferencesPath, JSON.stringify(preferences, null, 2));

    return { success: true };
  } catch (error) {
    return { success: false, error: (error as Error).message };
  }
});
